[project]
name = "kalufs-kepubify"
version = "0.1.0"
readme = "README.md"
description = "Small flask application for converting epub into kepub."
requires-python = ">=3.12"

dependencies = [
    "flask==3.1.3",
    "flask-reverse-proxy==0.2.0.2",
]

[dependency-groups]
dev = [
    "pyright>=1.1.414",
    "ruff",
]

[project.optional-dependencies]
server = [
    "gunicorn>=26.2.0",
]

[tool.pyright]
typeCheckingMode = "standard"

[tool.ruff]
line-length = 120
output-format = "grouped"

[tool.ruff.lint.pydocstyle]
convention = "google"
